### ISSUE TITLE
Checkpoints for finetuning

### ISSUE THREAD

**Issue by castdice** [jacobkrantz/IVLN-CE#2]
Hi, thank you for your excellent work. I have some problems replicating the experiment, could you please provide the best-performing checkpoints of first-stage training, i.e., the checkpoint to be loaded before finetuning? 

Thank you for your patience.

**Comment by jacobkrantz** [comment]
Hi @castdice,

https://drive.google.com/file/d/1Dc2dAqzIJ9cMsN0GFAP8EaIvW_xtrhfL/view?usp=sharing
Here is the checkpoint we obtained from first-stage training while using ground-truth semantics with iterative maps. This checkpoint led to the results of Tab. 4 rows 4-6. After this first-stage training, this model achieved {SR=17, SPL=16} in val-unseen. 

Were you able to reproduce the evaluations of the provided pre-trained models? This can be a good place to start as it has a quicker debugging turn-around than training models from scratch.

**Comment by castdice** [comment]
It is really helpful. I am still running the experiment, but the performance is close already. Thanks!
